#!/bin/bash

# Array of files to check
checks=( \
"/bin/bash" "/usr/sbin/sshd" '/bin/login' \
'/bin/su' '/usr/bin/sudo' '/usr/bin/yum' \
'/bin/rpm' '/usr/bin/dpkg' '/usr/bin/apt-get' \
)

# Debug true/false
debug="false"
debug_verbose="false"

usage () {
  cat << EOF
  ${0} checks checksums for files against local package database
  Usage: ${0} [-dvh] -p <file>

    Options:
      -d : debug
      -v : verbose (implies -d)
      -f <file>: list of files to check
      -h : Prints this list
EOF
}

while getopts dvhf: option; do
  case ${option} in
    d )
      debug="true"
      ;;
    v )
      debug="true"
      debug_verbose="true"
      ;;
    f )
      check_file=${OPTARG}
      unset checks
      line=0
      for lines in $(cat ${check_file}); do
        checks[${line}]=$(cat ${check_file}) # needs sanity check..
        line=((line+1))
      done
      ;;
    h|* )
      usage
      exit 1
      ;;
  esac
done

check_distro () {
  # Get distro and determine what checksum to use
  distro=$(lsb_release -a 2> /dev/null | awk '/Distributor/ {print $3}')
  distro_majrelease=$(lsb_release -a 2> /dev/null | awk '/Release/ {print $2}' | cut -d"." -f1)

  case ${distro} in
    Ubuntu|Debian )
      pkgmgr="dpkg"
      pkgmgr_digest="md5sum"
      ;;
    RedHatEnterpriseServer|CentOS|Scientific )
      pkgmgr="rpm"
      if [ ${distro_majrelease} -le 5 ]; then
        pkgmgr_digest="md5sum"
      else
        pkgmgr_digest="sha256sum"
      fi
      # Check if prelink is enabled.
      check_prelink=$(awk '/PRELINKING/ {print $1}' /etc/sysconfig/prelink | cut -d "=" -f2 )
      if [ ${check_prelink} == "yes" ]; then
        prelink_enabled="true"
      else
        prelink_enabled="false"
      fi
      ;;
    * )
      echo "Unknown Distro: Please fix me.. im broken.."
      exit 1
      ;;
  esac

  if [ ${debug} == "true" ]; then
    echo
    echo "function \"${FUNCNAME}\" - debug:"
    echo "  Distro          = ${distro}"
    echo "  Major release   = ${distro_majrelease}"
    echo "  Checksum util   = \"${pkgmgr}\""
    echo "  Prelink enabled = \"${prelink_enabled}\""
    echo
  fi

  return 0
}

check_file_exists () {
  # Check if file exists, if not, delete it from array.

  local index=0

  for file in ${checks[@]}; do
    if [ ! -f ${file} ]; then
      skiped_files[${index}]=${file}
      unset checks[${index}]
    fi
    let index=index+1
  done

  # Debug
  if [ ${debug} == "true" ]; then
    echo "function \"${FUNCNAME}\" - debug:"
    echo "  Files to check:"
    for file in ${checks[@]}; do
      echo "    ${file}"
    done
    echo
    echo "  Missing files:"
    for missing in ${skiped_files[@]}; do
      echo "    ${missing}"
    done
    echo
  fi

  return 0
}

get_package_name () {
  # Check if file is handled by package manager
  # Returns package name if claimd by package
  # Returns 1 and sets ${package_name} = "orpahned" if not
  local file=${1}

  case ${pkgmgr} in
    dpkg )
      package_name=$(dpkg -S ${file} | cut -d":" -f1) 2> /dev/null
      if [ ${PIPESTATUS[0]} -ne 0 ]; then
        package_name="orphaned"
      fi
      ;;
    rpm )
      package_name=$(rpm -qf ${file}) 2> /dev/null
      if [ $? -ne 0 ]; then
        package_name="orphaned"
      fi
      ;;
    * )
      echo "Oh lordi lord! function \"${FUNCNAME}\" failed, no such package manager"
      exit 2
      ;;
  esac

  # Debug
   if [ ${debug} == "true" ]; then
     if [ ${package_name} == "orphaned" ]; then
       echo "function \"${FUNCNAME}\" - debug:"
       echo "  \"${file}\" is orphaned, no package claims to own it."
       echo
     fi
     if [ ${debug_verbose} == "true" ]; then
       echo "function \"${FUNCNAME}\" - debug:"
       echo "  \"${file}\" is claimend by \"${package_name}\""
       echo
     fi
   fi

   if [ ${package_name} == "orphaned" ]; then
     orphaned_files+=( ${file} )
     return 1
   else
     return 0
   fi
}

rpm_check_file_digest () {
  #sjekker om prelink eksisterer og om filen ligger i prelink.cache 
  # og om den gjøre det så sumer vi via prelink -y
  local file_path=${1}
}

checksum () {
  # Takes 2 arguments;
  #  1) path from pseudo_file_name array element
  #  2) package_name from get_package_name()
  #  Returns: 0 if checksums are identical, and 1 if they differ.

  local file_path=${1}
  local package_name=${2}

  case ${pkgmgr} in
    dpkg )
      # Remove first char from path (/)
      # as ${package_name}.md5sums contains path without starting /
      file_path_mod=${file_path:1:${#file_path}}
      package_checksum=$(cat /var/lib/dpkg/info/${package_name}.md5sums | egrep "${file_path_mod}$" | awk '{print $1}')
      file_checksum=$(md5sum ${file_path} | awk '{print $1}')
      ;;
    rpm )
      # Rhel (and clones) use prelink, we have to use prelink -y to get correct checksums if enabled.
      local package_checksum=$(rpm -ql --dump ${package_name} | egrep "^${file_path} " | awk '{print $4}')

      if [ ${prelink_enabled} == "true" ]; then
        local in_prelink_cache=$(/usr/sbin/prelink -p | egrep "^${file_path}:|^${file_path} ")
        if [[ ${in_prelink_cache} =~ not.prelinkable ]]; then
          local prelink_match="not prelinkable"
          file_checksum=$( ${pkgmgr_digest} ${file_path} | awk '{print $1}')

        elif [[ ${in_prelink_cache} =~ ^${file_path}:$ ]]; then
          local prelink_match="true"
          file_checksum=$(prelink -y ${file_path} 2>/dev/null | ${pkgmgr_digest} | awk '{print $1}')
          # If prelink fails, we need to catch output
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
           prelink_status=$(prelink -y ${file_path} 1>/dev/null 2>&1)
          fi
        else
          local prelink_match="false"
          file_checksum=$(${pkgmgr_digest} ${file_path} | awk '{print $1}')
        fi
      fi
      ;;
    * )
      echo "Wat?! function \"${FUNCNAME}\" failed, \${pkgmgr} not known."
      exit 2
      ;;
  esac

  if [ ${debug_verbose} == "true" ]; then
    echo "function \"${FUNCNAME}\" - verbose debug:"
    echo "  Package name          = ${package_name}"
    echo "  File path             = ${file_path}"
    echo "  Package checksum      = ${package_checksum}"
    echo "  File checksum         = ${file_checksum}"
    echo "  File in prelink cache = ${prelink_match}"
    echo "  In prelink cache      = ${in_prelink_cache}"
    echo "  Prelink output        = ${prelink_status}"
    echo
  fi

  if [ ${file_checksum} != ${package_checksum} ]; then
    return 1
  elif [ -n ${prelink_status} ]; then
    return 2
  else
    return 0
  fi
}

do_checks () {
  # Itterates ${checks} array over checksum() function
  # and populates failed and verified arrays.

  local failed=0
  local verified=0
  local prelink=0

  for file in ${checks[@]}; do
    get_package_name ${file}
    if [ $? -eq 0 ]; then
      checksum ${file} ${package_name}
      if [ $? -eq 1 ]; then
        failed_files[${failed}]=${file}
        failed_packages[${failed}]=${package_name}
        failed=$((failed+1))
      elif [ $? -eq 2 ]; then
        failed_prelink_file[${prelink}]=${file}
        failed_prelink_package[${prelink}]=${package_name}
        prelink=$((prelink+1))
      else
        verified_files[${verified}]=${file}
        verified_packages[${verified}]=${package_name}
        verified=$((verified+1))
      fi
    fi
  done
  
  # Debug
  if [ ${debug} == "true" ]; then
    local prelink_count=0
    echo
    echo "Prelink has problems with these files:"
    for i in ${failed_prelink_files[@]}; do 
     echo "\"${failed_prelink_files[${prelink_count}]}\" in package \"${failed_prelink_packages[${prelink_count}]}\""
    done
    echo
    echo "A fix might be to reinstall these packages, or run prelink manualy"
    echo
  fi

  # Debug Verbose
  if [ ${debug_verbose} == "true" ]; then
    echo "function \"${FUNCNAME}\" - verbose debug:"

    echo "  #failed           = ${failed}"
    echo "  failed_files[@]   ="
    for i in ${failed_files[@]}; do
      echo "    ${i}"
    done
    echo
    echo "  failed_packages[@] ="
    for i in ${failed_packages[@]}; do
      echo "    ${i}"
    done
    echo
  
    echo "  #verified           = ${verified}"
    echo "  verified_files[@]   ="
    for i in ${verified_files[@]}; do
      echo "    ${i}"
    done
    echo
    echo "  verified_packages[@] ="
    for i in ${verified_packages[@]}; do
      echo "    ${i}"
    done
    echo

    echo " orhpaned_files[@] ="
    for i in ${orphaned_files[@]}; do
      echo "    ${i}"
    done
    echo
  fi

  return 0
}

output () {

  nagios_error=0
  local count=0

  if [ ${#failed_files[@]} -ne "0" ]; then
    echo "CRITICAL: File(s) did not match package checksum! Run \"${0} -d\" to investigate."
    for i in ${failed_files[@]}; do
        echo "${failed_files[${count}]} does not match ${failed_packages[${count}]}"
        let count=count+1
    done
    nagios_error=2
  elif [ ${#orphaned_files[@]} -ne "0" ]; then
    echo "WARNING: Trying to checksum orphaned files, run \"${0} -d\" for more info"
    nagios_error=1
  elif [ ${#failed_prelink_files[@]} -ne "0" ]; then
    echo "WARNING: Prelink failed on some files, run \"${0} -d\" for more info. Reinstalling packag(es) might fixes this"
    nagios_error=1
  else
    echo "OK: All checked files match package managers checksums."
  fi

  # Debug
  if [ ${debug_verbose} == "true" ] ; then
    echo
    echo "function \"${FUNCNAME}\" - verbose debug:"
    echo "  nagios_error = ${nagios_error}"
    echo
  fi

  return ${nagiso_error}
}

debug_output () {
  local count_failed=0
  local count_verified=0

  if [ ${debug} == "true" ]; then
    echo "function \"${FUNCNAME}\" - debug:"
    echo "  Affcted files/packages:"
    for i in ${failed_files[@]}; do
      echo "    \"${failed_files[${count_failed}]}\" does not match \"${failed_packages[${count_failed}]}\""
      let count_failed=count_failed+1
    done
    echo

    echo "  Verified files/packages:"
    for i in ${verified_files[@]}; do
      echo "    \"${verified_files[${count_verified}]}\" matches \"${verified_packages[${count_verified}]}\""
      let count_verified=count_verified+1
    done
    echo
  fi

  return 0
}

check_distro
check_file_exists
do_checks
debug_output
output
exit ${nagios_error}
